### ISSUE TITLE
many functions in `racket/function` don't work

### ISSUE THREAD

**Issue by stchang** [racketscript/racketscript#340]
`curry` and functions that use it (`disjoin`, etc) fail with error:

```
kw.rkt.js:1 Uncaught TypeError: M0.__rjs_quoted__.procedure_reduce_arity_mask is not a function
    at do_procedure_reduce_keyword_arity (kw.rkt.js:1:31840)
    at kw.rkt.js:1:43736
    at cl6692 (kw.rkt.js:1:43965)
    at kw.rkt.js:1:44375
    at cl6693 (kw.rkt.js:1:44107)
    at Module.<anonymous> (kw.rkt.js:1:44375)
    at make_curry (function.rkt.js:1:11426)
    at function.rkt.js:1:11871
```

**Comment by samth** [comment]
I think that procedure-reduce-arity-mask could just be the identity function for many purposes.
